/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppGameCodenames {
    }
    interface AppGameWhoIsTheSpy {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppWaitingZone {
        "roomName": string;
    }
}
declare global {
    interface HTMLAppGameCodenamesElement extends Components.AppGameCodenames, HTMLStencilElement {
    }
    var HTMLAppGameCodenamesElement: {
        prototype: HTMLAppGameCodenamesElement;
        new (): HTMLAppGameCodenamesElement;
    };
    interface HTMLAppGameWhoIsTheSpyElement extends Components.AppGameWhoIsTheSpy, HTMLStencilElement {
    }
    var HTMLAppGameWhoIsTheSpyElement: {
        prototype: HTMLAppGameWhoIsTheSpyElement;
        new (): HTMLAppGameWhoIsTheSpyElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppWaitingZoneElement extends Components.AppWaitingZone, HTMLStencilElement {
    }
    var HTMLAppWaitingZoneElement: {
        prototype: HTMLAppWaitingZoneElement;
        new (): HTMLAppWaitingZoneElement;
    };
    interface HTMLElementTagNameMap {
        "app-game-codenames": HTMLAppGameCodenamesElement;
        "app-game-who-is-the-spy": HTMLAppGameWhoIsTheSpyElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "app-waiting-zone": HTMLAppWaitingZoneElement;
    }
}
declare namespace LocalJSX {
    interface AppGameCodenames {
    }
    interface AppGameWhoIsTheSpy {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppWaitingZone {
        "roomName"?: string;
    }
    interface IntrinsicElements {
        "app-game-codenames": AppGameCodenames;
        "app-game-who-is-the-spy": AppGameWhoIsTheSpy;
        "app-home": AppHome;
        "app-root": AppRoot;
        "app-waiting-zone": AppWaitingZone;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-game-codenames": LocalJSX.AppGameCodenames & JSXBase.HTMLAttributes<HTMLAppGameCodenamesElement>;
            "app-game-who-is-the-spy": LocalJSX.AppGameWhoIsTheSpy & JSXBase.HTMLAttributes<HTMLAppGameWhoIsTheSpyElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-waiting-zone": LocalJSX.AppWaitingZone & JSXBase.HTMLAttributes<HTMLAppWaitingZoneElement>;
        }
    }
}
